"use strict";

export const TRANSACTION_LIST_REQUEST = 'TRANSACTION_LIST_REQUEST';
export const TRANSACTION_LIST_SUCCESS = 'TRANSACTION_LIST_SUCCESS';
export const TRANSACTION_LIST_FAILURE = 'TRANSACTION_LIST_FAILURE';

export const TRANSACTION_REMOVE_REQUEST = 'TRANSACTION_REMOVE_REQUEST';
export const TRANSACTION_REMOVE_SUCCESS = 'TRANSACTION_REMOVE_SUCCESS';
export const TRANSACTION_REMOVE_FAILURE = 'TRANSACTION_REMOVE_FAILURE';

export const TRANSACTION_ADD_REQUEST = 'TRANSACTION_ADD_REQUEST';
export const TRANSACTION_ADD_SUCCESS = 'TRANSACTION_ADD_SUCCESS';
export const TRANSACTION_ADD_FAILURE = 'TRANSACTION_ADD_FAILURE';